image: node:20

pages:
  cache:
    paths:
      - node_modules/
  script:
    - cd my-app
    - npm ci
    - npx @angular/cli build --configuration production --base-href ./
    - cp -r dist/flobite-local public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  tags:
    - app_shared_runner
  only:
    - flowbite-learning  # or your default branch
